/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quiz;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/*
 *
 * @author jonaskompatscher
 */
public class quiz_gui extends javax.swing.JFrame {
    

    /**
     * Creates new form quiz_gui
     */
    private JPanel mainPanel;
    private  QuizLogik logik;
    public quiz_gui() {
        initComponents();
        logik = new QuizLogik(this);
        logik.showQuestion();
        
               
    }
    
    
    public void mouseClicked(MouseEvent e) {
		
		int antwort = 0;
		if(e.getSource().equals(antworta)) {
			antwort =1;
		}else if(e.getSource().equals(antwortb)){
			antwort =2;
		}else if(e.getSource().equals(antwortc)){
			antwort =3;
		}else if(e.getSource().equals(antwortd)){
			antwort =4;
		}
		
		if(logik.checkAnswer(antwort)) {
			JOptionPane.showMessageDialog(this,"Richtig!!!");
		}else {
			JOptionPane.showMessageDialog(this,"Leider Falsch!!!");
		}
		
		if(logik.hasNextQuestion()) {
			logik.showQuestion();
		}else {
			JOptionPane.showMessageDialog(this,"Sie haben alle Fragen beantwortet");
		}
	}
    private void resetButtonColors() {
    antworta.setBackground(Color.blue);
    antwortb.setBackground(Color.blue);
    antwortc.setBackground(Color.blue);
    antwortd.setBackground(Color.blue);
    }
    public void setFrageText(String text) {
		frage.setText(text);
	}
	public void setAntwort1(String text) {
                antworta.setText(text);
	}
	public void setAntwort2(String text) {
		antwortb.setText(text);
	}
	public void setAntwort3(String text) {
		antwortc.setText(text);
	}
	public void setAntwort4(String text) {
		antwortd.setText(text);
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        antworta = new javax.swing.JButton();
        antwortb = new javax.swing.JButton();
        antwortc = new javax.swing.JButton();
        antwortd = new javax.swing.JButton();
        frage = new javax.swing.JButton();
        restart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quiz");

        antworta.setBackground(new java.awt.Color(0, 0, 255));
        antworta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        antworta.setForeground(new java.awt.Color(255, 255, 255));
        antworta.setText("A: ");
        antworta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antwortaActionPerformed(evt);
            }
        });

        antwortb.setBackground(new java.awt.Color(0, 0, 255));
        antwortb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        antwortb.setForeground(new java.awt.Color(255, 255, 255));
        antwortb.setText("B: ");
        antwortb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antwortbActionPerformed(evt);
            }
        });

        antwortc.setBackground(new java.awt.Color(0, 0, 255));
        antwortc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        antwortc.setForeground(new java.awt.Color(255, 255, 255));
        antwortc.setText("C:");
        antwortc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antwortcActionPerformed(evt);
            }
        });

        antwortd.setBackground(new java.awt.Color(0, 0, 255));
        antwortd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        antwortd.setForeground(new java.awt.Color(255, 255, 255));
        antwortd.setText("D:");
        antwortd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antwortdActionPerformed(evt);
            }
        });

        frage.setBackground(new java.awt.Color(0, 0, 255));
        frage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        frage.setForeground(new java.awt.Color(255, 255, 255));
        frage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frageActionPerformed(evt);
            }
        });

        restart.setBackground(new java.awt.Color(0, 51, 255));
        restart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        restart.setForeground(new java.awt.Color(255, 255, 255));
        restart.setText("restart");
        restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(restart)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(232, 232, 232))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(frage, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(antworta, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(antwortc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(antwortd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(antwortb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(68, 68, 68))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(81, 81, 81)
                .addComponent(frage, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(antworta)
                    .addComponent(antwortb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(antwortc)
                    .addComponent(antwortd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(restart)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static int counter_richtig=0;
    private void antwortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antwortaActionPerformed
        // TODO add your hand
        
               
        
        if (QuizLogik.checkAnswer(1)) {
            
            antworta.setBackground(Color.GREEN);
            JOptionPane.showMessageDialog(this, "Richtig");
            counter_richtig++;
            
        } else {
            antworta.setBackground(Color.RED);
            if(QuizLogik.checkAnswer(2)){
                antwortb.setBackground(Color.green);
            }
            if(QuizLogik.checkAnswer(3)){
                antwortc.setBackground(Color.green);
            }
            if(QuizLogik.checkAnswer(4)){
                antwortd.setBackground(Color.green);
            }
            JOptionPane.showMessageDialog(this, "Falsch");
            
            
        }
        
        if (QuizLogik.hasNextQuestion()) {
            QuizLogik.showQuestion();
              antworta.setBackground(Color.BLUE);
        } else {
            JOptionPane.showMessageDialog(this, "Von " + FileReader.counter + " Fragen haben Sie " + counter_richtig + " Fragen richtig!");
            JOptionPane.showMessageDialog(this, "Neue Fragen schreiben!");
            FileReader.counter=0;
            counter_richtig=0;
            setVisible(false);
            start_gui fenster = new start_gui();
            fenster.setVisible(true);
        }
        resetButtonColors();
        
       
      
       

        
    }//GEN-LAST:event_antwortaActionPerformed

    private void antwortbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antwortbActionPerformed
        // TODO add your handling code here:
        
        
        if (QuizLogik.checkAnswer(2)) {
            antwortb.setBackground(Color.GREEN);
            JOptionPane.showMessageDialog(this, "Richtig");
            counter_richtig++;
            
        } else {
            antwortb.setBackground(Color.RED);
            if(QuizLogik.checkAnswer(1)){
                antworta.setBackground(Color.green);
            }
            else if(QuizLogik.checkAnswer(3)){
                antwortc.setBackground(Color.green);
            }
            else if(QuizLogik.checkAnswer(4)){
                antwortd.setBackground(Color.green);
            }
            JOptionPane.showMessageDialog(this, "Falsch");
           
        }
        if (QuizLogik.hasNextQuestion()) {
            QuizLogik.showQuestion();
              antwortb.setBackground(Color.BLUE);
        } else {
            JOptionPane.showMessageDialog(this, "Von " + FileReader.counter + " Fragen haben Sie " + counter_richtig + " Fragen richtig!");
            JOptionPane.showMessageDialog(this, "Neue Fragen schreiben!");
            FileReader.counter=0;
            counter_richtig=0;
            setVisible(false);
            start_gui fenster = new start_gui();
            fenster.setVisible(true);
        }
        resetButtonColors();

    }//GEN-LAST:event_antwortbActionPerformed

    private void antwortcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antwortcActionPerformed
        // TODO add your handling code here:
     
        if (QuizLogik.checkAnswer(3)) {
            antwortc.setBackground(Color.GREEN);
            JOptionPane.showMessageDialog(this, "Richtig");
            counter_richtig++;
            
        } else {
            antwortc.setBackground(Color.RED);
            if(QuizLogik.checkAnswer(1)){
                antworta.setBackground(Color.green);
            }
           else if(QuizLogik.checkAnswer(2)){
                antwortb.setBackground(Color.green);
            }
          else  if(QuizLogik.checkAnswer(4)){
                antwortd.setBackground(Color.green);
            }
            JOptionPane.showMessageDialog(this, "Falsch");
            
        }
        if (QuizLogik.hasNextQuestion()) {
            QuizLogik.showQuestion();
            antwortc.setBackground(Color.BLUE);
        } else {
            JOptionPane.showMessageDialog(this, "Von " + FileReader.counter + " Fragen haben Sie " + counter_richtig + " Fragen richtig!");
            JOptionPane.showMessageDialog(this, "Neue Fragen schreiben!");
            FileReader.counter=0;
            counter_richtig=0;
            setVisible(false);
            start_gui fenster = new start_gui();
            fenster.setVisible(true);
            
        }
        resetButtonColors();
    }//GEN-LAST:event_antwortcActionPerformed

    private void antwortdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antwortdActionPerformed
        // TODO add your handling code here:
        
        if (QuizLogik.checkAnswer(4)) {
            antwortd.setBackground(Color.GREEN);
            JOptionPane.showMessageDialog(this, "Richtig");
            counter_richtig++;
            
        } else {
            antwortd.setBackground(Color.RED);
            if(QuizLogik.checkAnswer(2)){
                antwortb.setBackground(Color.green);
            }
          else  if(QuizLogik.checkAnswer(3)){
                antwortc.setBackground(Color.green);
            }
          else  if(QuizLogik.checkAnswer(1)){
                antworta.setBackground(Color.green);
            }
            JOptionPane.showMessageDialog(this, "Falsch");
            
        }
        if (QuizLogik.hasNextQuestion()) {
            QuizLogik.showQuestion();
              antwortd.setBackground(Color.BLUE);
        } else {
            JOptionPane.showMessageDialog(this, "Von " + FileReader.counter + " Fragen haben Sie " + counter_richtig + " Fragen richtig!");
            JOptionPane.showMessageDialog(this, "Neue Fragen schreiben!");
            FileReader.counter=0;
            counter_richtig=0;
            setVisible(false);
            start_gui fenster = new start_gui();
            fenster.setVisible(true);
            
            
        }
        resetButtonColors();

    }//GEN-LAST:event_antwortdActionPerformed

    private void frageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frageActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_frageActionPerformed

    private void restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartActionPerformed
        // TODO add your handling code here:
        this.dispose();
    quiz_gui fenster = new quiz_gui();
        fenster.setVisible(true);
        
    }//GEN-LAST:event_restartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quiz_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quiz_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quiz_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quiz_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quiz_gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton antworta;
    private javax.swing.JButton antwortb;
    private javax.swing.JButton antwortc;
    private javax.swing.JButton antwortd;
    private javax.swing.JButton frage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton restart;
    // End of variables declaration//GEN-END:variables
}
