/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package textadventure;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import static textadventure.FileReader.reader;

/**
 *
 * @author JKompatscher
 */
public class game_gui extends javax.swing.JFrame {

    /**
     * Creates new form game_gui
     */
    public game_gui() {
        initComponents();
        this.setResizable(false);
        ImageIcon cov = new ImageIcon("first_scene.png");
        backpic_label.setIcon(cov);
        text.setBackground(Color.WHITE);
        text.setText(reader(5));
        //AudioPlayer_logik.start(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        ueberschrift = new javax.swing.JLabel();
        left_button = new javax.swing.JButton();
        right_button = new javax.swing.JButton();
        restart_button = new javax.swing.JButton();
        sound_button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        backpic_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text.setBackground(new java.awt.Color(255, 255, 255));
        text.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 650, 350));

        status.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 280, 40));

        ueberschrift.setBackground(new java.awt.Color(255, 255, 255));
        ueberschrift.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ueberschrift.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ueberschrift.setText("Traces of Terror");
        getContentPane().add(ueberschrift, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 48, 230, 40));

        left_button.setText("Crowbar");
        left_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                left_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(left_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, 140, 110));

        right_button.setText("Use Spatula");
        right_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                right_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(right_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 580, 140, 100));

        restart_button.setText("Restart");
        restart_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restart_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(restart_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 640, 120, 70));

        sound_button.setText("sound on");
        sound_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sound_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(sound_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 670, 430));
        getContentPane().add(backpic_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String lastRoom = "ent";
    Boolean beeninLiv = false;
//exportieren

    //int b = 1;
    int d = 5;
    int b = 1;
    boolean sound = true;

    private void left_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_left_buttonActionPerformed
        if (d == 5) { //used crowbar
            d = 1;
            text.setBackground(Color.WHITE);
            text.setText(reader(1));
            left_button.setText("");
            right_button.setText("");
            status.setText("YOU LOST!");
            ImageIcon cov = new ImageIcon("first_scene.png");
            backpic_label.setIcon(cov);
        } else if (d == 8) { //stairs up
            d = 13;
            text.setBackground(Color.WHITE);
            text.setText(reader(13));
            left_button.setText("Turn Left");
            right_button.setText("Turn Right");
            ImageIcon cov = new ImageIcon(backpicture_out.backpicture(d));
            backpic_label.setIcon(cov);
        } else if (d == 7) {
            d = 5;
            text.setBackground(Color.WHITE);
            text.setText(reader(7));
            left_button.setText("");
            right_button.setText("");
            status.setText("YOU LOST!");
            ImageIcon cov = new ImageIcon(backpicture_out.backpicture(d));
            backpic_label.setIcon(cov);
        } else if (d == 12) {
            d = 4;
            text.setBackground(Color.WHITE);
            text.setText(reader(4));
            left_button.setText("Rescue Manuel");
            right_button.setText("Run out of medical room");
            ImageIcon cov = new ImageIcon(backpicture_out.backpicture(d));
            backpic_label.setIcon(cov);
        } else if (d == 11) {//FEHLER --- NEIN! 
            d = 14;
            text.setBackground(Color.WHITE);
            text.setText(reader(14));
            left_button.setText("Drop weapon");
            right_button.setText("Drop Weapon");
            status.setText("YOU LOST!");
            ImageIcon cov = new ImageIcon(backpicture_out.backpicture(d));
            backpic_label.setIcon(cov);
        } else if (d == 13) {
            d = 7;
            text.setBackground(Color.WHITE);
            text.setText(reader(7));
            left_button.setText("");
            right_button.setText("");
            status.setText("YOU LOST!!");
            ImageIcon cov = new ImageIcon(backpicture_out.backpicture(d));
            backpic_label.setIcon(cov);
        } else if (d == 14) {
            d = 3;
            text.setBackground(Color.WHITE);
            text.setText(reader(3));
            left_button.setText("");
            right_button.setText("");
            status.setText("YOU LOST!!");
            ImageIcon cov = new ImageIcon(backpicture_out.backpicture(d));
            backpic_label.setIcon(cov);
        } else if (d == 16) {
            d = 2;
            text.setBackground(Color.WHITE);
            text.setText(reader(2));
            left_button.setText("");
            right_button.setText("");
            status.setText("YOU WON!");
            ImageIcon cov = new ImageIcon(backpicture_out.backpicture(d));
            backpic_label.setIcon(cov);
        }
        System.out.println(d);
    }//GEN-LAST:event_left_buttonActionPerformed

    private void right_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_right_buttonActionPerformed
        if (d == 5) { //opened window
            d = 8;
            text.setBackground(Color.WHITE);
            text.setText(reader(8));
            left_button.setText("stairs up");
            right_button.setText("stairs down");
            ImageIcon cov = new ImageIcon(backpicture_out.backpicture(d));
            backpic_label.setIcon(cov);
        } else if (d == 8) { //stairs down
            d = 12;
            text.setBackground(Color.WHITE);
            text.setText(reader(12));
            left_button.setText("Enter medical room");
            right_button.setText("Throw Hammer");
            ImageIcon cov = new ImageIcon(backpicture_out.backpicture(d));
            backpic_label.setIcon(cov);
        } else if (d == 12) {
            d = 15;
            text.setBackground(Color.WHITE);
            text.setText(reader(15));
            left_button.setText("Stairs Up");
            right_button.setText("Stairs Up");
            ImageIcon cov = new ImageIcon(backpicture_out.backpicture(d));
            backpic_label.setIcon(cov);
        } else if (d == 15) {
            d = 13;
            text.setBackground(Color.WHITE);
            text.setText(reader(13));
            left_button.setText("Turn Left");
            right_button.setText("Turn Right");
            ImageIcon cov = new ImageIcon(backpicture_out.backpicture(d));
            backpic_label.setIcon(cov);
        } else if (d == 13) {
            d = 10;
            text.setBackground(Color.WHITE);
            text.setText(reader(10));
            left_button.setText("");
            right_button.setText("");
            status.setText("YOU WON!");
            ImageIcon cov = new ImageIcon(backpicture_out.backpicture(d));
            backpic_label.setIcon(cov);
        } else if (d == 11) {
            d = 16;
            text.setBackground(Color.WHITE);
            text.setText(reader(16));
            left_button.setText("Jump out the broken window");
            right_button.setText("Jump out the broken window");
            ImageIcon cov = new ImageIcon(backpicture_out.backpicture(d));
            backpic_label.setIcon(cov);
        } else if (d == 16) {
            d = 2;
            text.setBackground(Color.WHITE);
            text.setText(reader(2));
            left_button.setText("");
            right_button.setText("");
            status.setText("YOU WON!");
            ImageIcon cov = new ImageIcon(backpicture_out.backpicture(d));
            backpic_label.setIcon(cov);
        } else if (d == 14) {
            d = 3;
            text.setBackground(Color.WHITE);
            text.setText(reader(3));
            left_button.setText("");
            right_button.setText("");
            status.setText("YOU LOST!!");
            ImageIcon cov = new ImageIcon(backpicture_out.backpicture(d));
            backpic_label.setIcon(cov);
        } else if (d == 4) {
            d = 11;
            text.setBackground(Color.WHITE);
            text.setText(reader(11));
            left_button.setText("Stay in the Living Room");
            right_button.setText("Go to Work Room");
            ImageIcon cov = new ImageIcon(backpicture_out.backpicture(d));
            backpic_label.setIcon(cov);
        } else if (d == 7) {
            d = 5;
            text.setBackground(Color.WHITE);
            text.setText(reader(7));
            left_button.setText("");
            right_button.setText("");
            status.setText("YOU LOST!");
            ImageIcon cov = new ImageIcon(backpicture_out.backpicture(d));
            backpic_label.setIcon(cov);
        }

    }//GEN-LAST:event_right_buttonActionPerformed

    private void restart_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restart_buttonActionPerformed
        new Start_gui().setVisible(true);
    }//GEN-LAST:event_restart_buttonActionPerformed

    private void sound_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sound_buttonActionPerformed
        if (sound) {
            sound_button.setText("sound off");
            AudioPlayer_logik.reset();
            sound = false;
        } else {
            sound_button.setText("sound on");
            AudioPlayer_logik.start(0);
            sound = true;
        }
    }//GEN-LAST:event_sound_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game_gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backpic_label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton left_button;
    private javax.swing.JButton restart_button;
    private javax.swing.JButton right_button;
    private javax.swing.JButton sound_button;
    private javax.swing.JLabel status;
    private javax.swing.JLabel text;
    private javax.swing.JLabel ueberschrift;
    // End of variables declaration//GEN-END:variables
}
